name: Build and push docker image
on:
  push:
    branches:
      - test/devops
  pull_request:
    types: [closed]
    branches:
      - main
      - cloud-deploy

jobs:
    build_image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4      
              
            - name: Login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push docker image
              uses: docker/build-push-action@v5
              with:
                context: ./src/Myflix.AuthService
                push: true
                tags: sandside/myflix:auth